### ISSUE TITLE
GraphQL subscriptions support

### ISSUE THREAD

**Issue by marco-lavagnino** [graphql-python/sanic-graphql#10]
What would be needed to support GraphQL subscriptions?

Like in [this link](http://dev.apollodata.com/tools/#GraphQL-subscriptions)

**Comment by grazor** [comment]
Hi, @marco-lavagnino!

Subscription support first needs to be implemented in [core Python GraphQL realization](https://github.com/graphql-python/graphql-core). Unfortunately it's far too behind from origin [JavaScript implementation](https://github.com/graphql/graphql-js) (v0.6.0 and v0.11.3 respectively).

The best one could do is to help to upgrade core lib to the latest versions. See [issue #75](https://github.com/graphql-python/graphql-core/issues/75).

**Comment by mandx** [comment]
What about this: https://github.com/graphql-python/graphql-ws?

**Comment by ProjectCheshire** [comment]
@mandx after hunting in what feels like everywhere, your comment <3 i was about to lose my mind on this and was dumbfounded it could be this far behind

**Comment by mandx** [comment]
@ProjectCheshire I feel you; the main problem with graphql-python/Graphene is the lack documentation, I had (and still have) to read a lot of internal code to get some pointers on what to do, what to write to accomplish what I want. On the flip side, I have been able to accomplish pretty much everything!
