### ISSUE TITLE
Broken with graphql-core==3.0.0

### ISSUE THREAD

**Issue by cuyu** [graphql-python/sanic-graphql#18]
My code is broken after using graphql-core==3.0.0:

```
Traceback (most recent call last):
  File "./web_backend/server.py", line 3, in <module>
    from sanic_graphql import GraphQLView
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.7/site-packages/sanic_graphql/__init__.py", line 1, in <module>
    from .graphqlview import GraphQLView
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.7/site-packages/sanic_graphql/graphqlview.py", line 10, in <module>
    from graphql.execution.executors.asyncio import AsyncioExecutor
ModuleNotFoundError: No module named 'graphql.execution.executors
```

**Comment by Cito** [comment]
The requirements in setup.py,  'graphql-core>=2.1', and 'graphql-server-core>=1.1.1', both need a restriction "..,<3". Maybe sanic needs a restriction as well. I will try to push a release fixed release to PyPI this week. As a workaround, you can first install graphql-core<3, and then sanic-graphql.

**Comment by johndiego** [comment]
same error !!

**Comment by grammy-jiang** [comment]
I met the same error.

The version of `graphql-core` is not restricted.

The version 3 of the package of [graphql-python/graphql-core](https://github.com/graphql-python/graphql-core) is not backward-compatible with version 2.

I haven't got time to check the solution.

**Comment by grammy-jiang** [comment]
Just note, until today, the major project of graphql - [graphql-python/graphene](https://github.com/graphql-python/graphene) v2.1.8 - is still working with "graphql-core>=2.1,<3", while it just release a beta version 3.0.0b2 with graphql-core v3+ required.

**Comment by Cito** [comment]
@jkimbo can you push a 1.2.0 release to solve this? I'm missing the permissions on PyPI, but you should be able to do that.

**Comment by jkimbo** [comment]
@Cito done. v1.2.0 is now available on PyPi (sorry it's taken so long to do this).

**Comment by Cito** [comment]
You meant *now* not *not* - thank you!

Now we can also start updating this project to core v3.

**Comment by grammy-jiang** [comment]
Nice to have a new release with version fixed.

And one more thing - now Sanic version is fixed lower than 19, which is 20.6.3 now. If the next release can compatible with the latest Sanic version, it will be very good.

**Comment by grammy-jiang** [comment]
Also, if the version of this package can be embedded as `__version__`, it will be great.

**Comment by jkimbo** [comment]
Good point @grammy-jiang . We’re currently in the process of merging all the server integrations into the graphql-server package (see https://github.com/graphql-python/graphql-server-core/issues/34) so I’ve created an issue there to expose the version attribute: https://github.com/graphql-python/graphql-server-core/issues/47
